pools/pools/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include('profiles.urls')),
]

pools/profiles/urls.py
from django.conf.urls import url, include
from profiles import views

app_name = 'profiles'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/', views.user_logout, name="logout"),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

pools/profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    '''
    OneToOneField(User) will extend the class User and all it's fields, while also letting us add new fields
    that the User class does not have
    '''
    user = models.OneToOneField(User)

    '''
    additional fields will be portfolio_site and profile picture
    '''
    
    
    # blank=True means that field is not mandatory
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username
        

pools/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from profiles.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

pools/profiles/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from profiles.forms import UserForm, UserProfileInfoForm


from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse


from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request, 'profiles/home.html')

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic'in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'profiles/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print('worked')
                return redirect('/profiles/profile')
            else:
                return HttpResponse("YOU ARE NOT LOGGED IN!")
        print("Someone tried to login and failed!")
        return HttpResponse("invalid details")
    else:
        return render(request, "profiles/login.html")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    args = {'user': request.user}
    return render(request, 'profiles/profile.html', args)

pools/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Document</title>
</head>
<body>
        <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand" href="#">WebSiteName</a>
                  </div>
                  <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="{% url 'profiles:home' %}">Home</a></li>
                      <li class="dropdown">
                        <a href="{% url 'profiles:register' %}">Register </a>
                        
                      </li>
                      <li><a href="#">Page 2</a></li>
                      <li><a href="#">Page 3</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up {{ user.username }}</a></li>
                      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    </ul>
                  </div>
                </div>
              </nav>
    
    {% block content %}
    {% endblock %}
</body>
</html>

pools/templates/profiles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>My App</title>
</head>
<body>
        <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand" href="{% url 'profiles:home' %}">WebSiteName</a>
                  </div>
                  <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                      <li><a href="{% url 'profiles:home' %}">Home</a></li>
                    
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      {% if user.is_authenticated %}
                      <li><a href="{% url 'profiles:profile' %}">{{ user.username }}</a></li>
                      <li><a href="{% url 'profiles:logout' %}">Logout</a></li>
                      {% else %}
                      <li><a href="{% url 'profiles:register' %}">Register </a></li>
                      <li><a href="{% url 'profiles:login' %}">Login </a></li>
                      {% endif %}
                    </ul>
                  </div>
                </div>
              </nav>
    
    {% block content %}
    {% endblock %}
</body>
</html>

pools/templates/profiles/home.html
{% extends 'profiles/base.html'%}

{% block content %}
<h1 class="title">Welcome to the home page</h1>

{% endblock %}

pools/templates/profiles/index.html
{% extends 'base.html'%}

{% block content %}
<h1 class="title">Registration</h1>
<form method="post">
 {% csrf_token %}
 {{ form.as_p }}
 <input type="submit" value="Submit">
</form>
{% endblock %}

pools/templates/profiles/login.html
{% extends 'profiles/base.html'%}

{% block content %}
<h1 class="title">Please Login</h1>

<form action="{% url 'profiles:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password: </label>
    <input type="text" name="password" placeholder="Enter Password">
    <input type="submit" value="Login">
</form>

{% endblock %}

pools/templates/profiles/profile.html
{% extends 'profiles/base.html'%}

{% block content %}

    Profiles
    <h2>{{ user.get_full_name }}</h2>
    <ul>
    <li>Username: {{ user.username }}</li>
    <li>Location: {{ user.password }}</li>
    <li>Birth Date: {{ user.profile.birth_date }}</li>
    </ul>
{% endblock %}

pools/templates/profiles/register.html
{% extends 'profiles/base.html'%}

{% block content %}
<h1 class="title">Registration</h1>
<div>
    {% if registered %}
        <h1>Thank you for registering</h1>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="register">
    </form>
</div>
{% endblock %}